apiVersion: v1
kind: Service
metadata:
  name: {{ include "dnsmasq.fullname" . }}
  labels:
    {{- include "dnsmasq.labels" . | nindent 4 }}
  {{- if .Values.service.ipAddressResourceGroup }}
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-resource-group: {{ .Values.service.ipAddressResourceGroup }}
  {{- end }}
spec:
  {{- if .Values.service.ipAddress }}
  loadBalancerIP: {{ .Values.service.ipAddress }}
  {{- end}}
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 53
      protocol: UDP
      name: dns
  selector:
    {{- include "dnsmasq.selectorLabels" . | nindent 4 }}
